FROM ubuntu:16.04
RUN apt-get -y update
RUN apt-get install clang make automake libsdl1.2-dev libogg-dev libsdl-image1.2-dev libcurl4-openssl-dev libopenal-dev libvorbis-dev openssl libssl-dev -y
ENTRYPOINT /bin/bash
