.PHONY: default
default:
	xcodebuild -project assaultcube.xcodeproj -target assaultcube -configuration Release clean build
	xcodebuild -project assaultcube.xcodeproj -target launcher -configuration Release clean build
